-- Competitor Analysis Snowflake setup
-- Target database/schema: COMMUNICATIONS__EU__DER__DEV.DEV
-- Full workspace state and generation JSON should use the existing STRATEGIC_WORKSPACE
-- table when its contract supports the required access pattern. These tables are
-- structured/searchable indexes and operational records.

USE DATABASE COMMUNICATIONS__EU__DER__DEV;
USE SCHEMA DEV;

CREATE TABLE IF NOT EXISTS COMPETITOR_ANALYSIS_PROJECT_INDEX (
  PROJECT_ID STRING NOT NULL,
  PROJECT_NAME STRING,
  DISEASE STRING,
  ASSET STRING,
  MECHANISM STRING,
  GEOGRAPHY STRING,
  TIME_HORIZON STRING,
  OBJECTIVE STRING,
  WORKSPACE_KEY STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (PROJECT_ID)
);

CREATE TABLE IF NOT EXISTS COMPETITOR_ANALYSIS_EVIDENCE_ITEMS (
  EVIDENCE_ID STRING NOT NULL,
  PROJECT_ID STRING NOT NULL,
  SOURCE_FAMILY STRING NOT NULL,
  SOURCE_ID STRING,
  TITLE STRING,
  SUMMARY STRING,
  URL STRING,
  CONFIDENCE FLOAT,
  VALIDATION_STATUS STRING,
  EVIDENCE_LABEL STRING,
  RETRIEVED_AT TIMESTAMP_NTZ,
  EXCLUDED BOOLEAN DEFAULT FALSE,
  RAW_PAYLOAD VARIANT,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (EVIDENCE_ID)
);

CREATE TABLE IF NOT EXISTS COMPETITOR_ANALYSIS_SOURCE_RUNS (
  SOURCE_RUN_ID STRING NOT NULL,
  PROJECT_ID STRING NOT NULL,
  SOURCE_FAMILIES ARRAY,
  QUERY_JSON VARIANT,
  STATUS STRING,
  RESULT_COUNTS VARIANT,
  ERROR_MESSAGE STRING,
  STARTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  FINISHED_AT TIMESTAMP_NTZ,
  PRIMARY KEY (SOURCE_RUN_ID)
);

CREATE TABLE IF NOT EXISTS COMPETITOR_ANALYSIS_EXPORT_JOBS (
  EXPORT_JOB_ID STRING NOT NULL,
  PROJECT_ID STRING NOT NULL,
  EXPORT_TYPE STRING NOT NULL,
  STATUS STRING NOT NULL,
  REQUEST_JSON VARIANT,
  OUTPUT_URI STRING,
  ERROR_MESSAGE STRING,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  FINISHED_AT TIMESTAMP_NTZ,
  PRIMARY KEY (EXPORT_JOB_ID)
);

CREATE TABLE IF NOT EXISTS COMPETITOR_ANALYSIS_AUDIT_LOG (
  AUDIT_ID STRING NOT NULL,
  PROJECT_ID STRING,
  ACTOR STRING DEFAULT 'local-user',
  ACTION STRING NOT NULL,
  DETAIL_JSON VARIANT,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (AUDIT_ID)
);

COMMENT ON TABLE COMPETITOR_ANALYSIS_PROJECT_INDEX IS
  'Searchable project index for Competitor Analysis. Full state is stored in STRATEGIC_WORKSPACE where possible.';

COMMENT ON TABLE COMPETITOR_ANALYSIS_EVIDENCE_ITEMS IS
  'Normalized and raw validated source evidence for Competitor Analysis.';

COMMENT ON TABLE COMPETITOR_ANALYSIS_SOURCE_RUNS IS
  'Operational records for PubMed, ClinicalTrials.gov, FDA, EMA, company, congress, guideline, HTA/payer, and news retrieval runs.';

COMMENT ON TABLE COMPETITOR_ANALYSIS_EXPORT_JOBS IS
  'Backend PDF and PowerPoint export job records.';

COMMENT ON TABLE COMPETITOR_ANALYSIS_AUDIT_LOG IS
  'Audit events for workspace, evidence, generation, regeneration, and export actions.';
