USE WAREHOUSE WH_COMMUNICATIONS__EU__DER;
USE DATABASE COMMUNICATIONS__EU__DER__DEV;
USE SCHEMA PFIZER_ANTIINF;

CREATE OR REPLACE CORTEX SEARCH SERVICE KNOWLEDGE_SEARCH
    ON SEARCH_TEXT
    PRIMARY KEY (CHUNK_ID)
    ATTRIBUTES
        COLLECTION_ID,
        DOCUMENT_ID,
        SECURITY_DOMAIN,
        LANGUAGE,
        DOCUMENT_TYPE,
        EFFECTIVE_FROM,
        EFFECTIVE_TO,
        DOCUMENT_STATUS,
        EVIDENCE_TYPE,
        UPDATED_AT
    WAREHOUSE = WH_COMMUNICATIONS__EU__DER
    TARGET_LAG = '5 minutes'
    EMBEDDING_MODEL = 'snowflake-arctic-embed-m-v1.5'
    REFRESH_MODE = INCREMENTAL
    REQUEST_LOGGING = TRUE
    COMMENT = 'Hybrid retrieval index over published PFIZER ANTIINF chunks.'
AS
SELECT
    CHUNK_ID,
    SEARCH_TEXT,
    CHUNK_TEXT,
    DOCUMENT_ID,
    VERSION,
    COLLECTION_ID,
    SECURITY_DOMAIN,
    LANGUAGE,
    DOCUMENT_TYPE,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    PAGE_FROM,
    PAGE_TO,
    SECTION_PATH,
    CHUNK_CHARACTER_COUNT,
    SEARCH_CHARACTER_COUNT,
    SEARCH_TOKEN_COUNT,
    CHUNKING_STRATEGY,
    CHUNKER_VERSION,
    TITLE,
    ORIGINAL_FILENAME,
    STAGE_RELATIVE_PATH,
    EVIDENCE_TYPE,
    IMAGE_ID,
    IMAGE_STAGE_RELATIVE_PATH,
    DOCUMENT_STATUS,
    UPDATED_AT
FROM KNOWLEDGE_CHUNKS
WHERE DOCUMENT_STATUS = 'PUBLISHED';

SHOW CORTEX SEARCH SERVICES LIKE 'KNOWLEDGE_SEARCH' IN SCHEMA PFIZER_ANTIINF;
