USE WAREHOUSE WH_COMMUNICATIONS__EU__DER;
USE DATABASE COMMUNICATIONS__EU__DER__DEV;

CREATE SCHEMA IF NOT EXISTS PFIZER_ANTIINF
    COMMENT = 'Independent Snowflake-native PFIZER ANTIINF Cortex Knowledge Hub application.';

USE SCHEMA PFIZER_ANTIINF;

CREATE STAGE IF NOT EXISTS KNOWLEDGE_FILES
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    COMMENT = 'Authoritative versioned source files for PFIZER ANTIINF.';

CREATE STAGE IF NOT EXISTS PFIZER_ANTIINF_STREAMLIT_STAGE
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    COMMENT = 'Application source files for the PFIZER ANTIINF Streamlit app.';

CREATE TABLE IF NOT EXISTS KNOWLEDGE_COLLECTIONS (
    COLLECTION_ID VARCHAR NOT NULL,
    COLLECTION_NAME VARCHAR NOT NULL,
    DESCRIPTION VARCHAR,
    DEFAULT_LANGUAGE VARCHAR DEFAULT 'English',
    SECURITY_DOMAIN VARCHAR NOT NULL DEFAULT 'INTERNAL',
    INGESTION_CONFIG VARIANT,
    SEARCH_CONFIG VARIANT,
    STATUS VARCHAR NOT NULL DEFAULT 'ACTIVE',
    CREATED_BY VARCHAR NOT NULL,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_KNOWLEDGE_COLLECTIONS PRIMARY KEY (COLLECTION_ID)
)
COMMENT = 'Governed knowledge collections and their ingestion/search defaults.';

CREATE TABLE IF NOT EXISTS KNOWLEDGE_COLLECTION_ACL (
    COLLECTION_ID VARCHAR NOT NULL,
    PRINCIPAL_TYPE VARCHAR NOT NULL,
    PRINCIPAL_NAME VARCHAR NOT NULL,
    PERMISSION VARCHAR NOT NULL,
    GRANTED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    GRANTED_BY VARCHAR NOT NULL,
    CONSTRAINT PK_KNOWLEDGE_COLLECTION_ACL
        PRIMARY KEY (COLLECTION_ID, PRINCIPAL_TYPE, PRINCIPAL_NAME, PERMISSION)
)
COMMENT = 'Application-level READ, UPLOAD, PUBLISH, and ADMIN permissions.';

CREATE TABLE IF NOT EXISTS KNOWLEDGE_DOCUMENTS (
    DOCUMENT_ID VARCHAR NOT NULL,
    VERSION NUMBER(10,0) NOT NULL,
    COLLECTION_ID VARCHAR NOT NULL,
    SECURITY_DOMAIN VARCHAR NOT NULL,
    TITLE VARCHAR NOT NULL,
    ORIGINAL_FILENAME VARCHAR NOT NULL,
    STAGE_RELATIVE_PATH VARCHAR NOT NULL,
    SHA256 VARCHAR NOT NULL,
    MIME_TYPE VARCHAR,
    FILE_SIZE_BYTES NUMBER(38,0),
    LANGUAGE VARCHAR,
    DOCUMENT_TYPE VARCHAR,
    EFFECTIVE_FROM DATE,
    EFFECTIVE_TO DATE,
    STATUS VARCHAR NOT NULL DEFAULT 'UPLOADED',
    IS_CURRENT_VERSION BOOLEAN NOT NULL DEFAULT TRUE,
    PAGE_COUNT NUMBER(10,0) DEFAULT 0,
    CHUNK_COUNT NUMBER(10,0) DEFAULT 0,
    IMAGE_COUNT NUMBER(10,0) DEFAULT 0,
    IMAGE_WARNING_COUNT NUMBER(10,0) DEFAULT 0,
    UPLOADED_BY VARCHAR NOT NULL,
    UPLOADED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PUBLISHED_BY VARCHAR,
    PUBLISHED_AT TIMESTAMP_NTZ,
    METADATA VARIANT,
    PROCESSING_VERSION VARCHAR NOT NULL DEFAULT 'knowledge-hub-v3-page-aware',
    PROCESSING_WARNINGS VARIANT,
    ERROR_DETAILS VARIANT,
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_KNOWLEDGE_DOCUMENTS PRIMARY KEY (DOCUMENT_ID, VERSION)
)
COMMENT = 'Authoritative document/version manifest. Files remain in KNOWLEDGE_FILES.';

CREATE TABLE IF NOT EXISTS KNOWLEDGE_DOCUMENT_PAGES (
    DOCUMENT_ID VARCHAR NOT NULL,
    VERSION NUMBER(10,0) NOT NULL,
    PAGE_NUMBER NUMBER(10,0) NOT NULL,
    PAGE_MARKDOWN VARCHAR,
    PARSER_NAME VARCHAR NOT NULL,
    PARSER_VERSION VARCHAR,
    PARSED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_KNOWLEDGE_DOCUMENT_PAGES
        PRIMARY KEY (DOCUMENT_ID, VERSION, PAGE_NUMBER)
)
COMMENT = 'Page-level parsed Markdown used for citations, previews, and rechunking.';

CREATE TABLE IF NOT EXISTS KNOWLEDGE_DOCUMENT_IMAGES (
    IMAGE_ID VARCHAR NOT NULL,
    DOCUMENT_ID VARCHAR NOT NULL,
    VERSION NUMBER(10,0) NOT NULL,
    PAGE_NUMBER NUMBER(10,0) NOT NULL,
    IMAGE_INDEX NUMBER(10,0) NOT NULL,
    SOURCE_IMAGE_ID VARCHAR,
    BOUNDING_BOX VARIANT,
    MIME_TYPE VARCHAR,
    STAGE_RELATIVE_PATH VARCHAR,
    CONTENT_HASH VARCHAR,
    IMAGE_TYPE VARCHAR,
    IS_INFORMATION_BEARING BOOLEAN,
    EXTRACTED_TEXT VARCHAR,
    DESCRIPTION VARCHAR,
    STRUCTURED_CONTENT VARIANT,
    ANALYSIS_STATUS VARCHAR NOT NULL,
    MODEL VARCHAR,
    CONFIDENCE_SCORES VARIANT,
    ERROR_DETAILS VARIANT,
    PROCESSING_VERSION VARCHAR NOT NULL,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_KNOWLEDGE_DOCUMENT_IMAGES PRIMARY KEY (IMAGE_ID)
)
COMMENT = 'Governed extracted-image inventory with page provenance and vision analysis.';

CREATE TABLE IF NOT EXISTS KNOWLEDGE_CHUNKS (
    CHUNK_ID VARCHAR NOT NULL,
    DOCUMENT_ID VARCHAR NOT NULL,
    VERSION NUMBER(10,0) NOT NULL,
    COLLECTION_ID VARCHAR NOT NULL,
    SECURITY_DOMAIN VARCHAR NOT NULL,
    CHUNK_NUMBER NUMBER(10,0) NOT NULL,
    PAGE_FROM NUMBER(10,0),
    PAGE_TO NUMBER(10,0),
    SECTION_PATH VARCHAR,
    CHUNK_TEXT VARCHAR NOT NULL,
    SEARCH_TEXT VARCHAR NOT NULL,
    CHUNK_CHARACTER_COUNT NUMBER(10,0),
    SEARCH_CHARACTER_COUNT NUMBER(10,0),
    SEARCH_TOKEN_COUNT NUMBER(10,0),
    CHUNKING_STRATEGY VARCHAR,
    CHUNKER_VERSION VARCHAR,
    TITLE VARCHAR NOT NULL,
    ORIGINAL_FILENAME VARCHAR NOT NULL,
    STAGE_RELATIVE_PATH VARCHAR NOT NULL,
    LANGUAGE VARCHAR,
    DOCUMENT_TYPE VARCHAR,
    EFFECTIVE_FROM DATE,
    EFFECTIVE_TO DATE,
    EFFECTIVE_TAGS VARIANT,
    DOCUMENT_STATUS VARCHAR NOT NULL,
    METADATA VARIANT,
    PROCESSING_VERSION VARCHAR NOT NULL,
    EVIDENCE_TYPE VARCHAR DEFAULT 'TEXT',
    IMAGE_ID VARCHAR,
    IMAGE_STAGE_RELATIVE_PATH VARCHAR,
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_KNOWLEDGE_CHUNKS PRIMARY KEY (CHUNK_ID)
)
CHANGE_TRACKING = TRUE
COMMENT = 'Citation-preserving retrieval chunks; published rows feed Cortex Search.';

-- Backward-compatible migration for environments created before markdown_section_v2.
ALTER TABLE KNOWLEDGE_CHUNKS ADD COLUMN IF NOT EXISTS CHUNK_CHARACTER_COUNT NUMBER(10,0);
ALTER TABLE KNOWLEDGE_CHUNKS ADD COLUMN IF NOT EXISTS SEARCH_CHARACTER_COUNT NUMBER(10,0);
ALTER TABLE KNOWLEDGE_CHUNKS ADD COLUMN IF NOT EXISTS SEARCH_TOKEN_COUNT NUMBER(10,0);
ALTER TABLE KNOWLEDGE_CHUNKS ADD COLUMN IF NOT EXISTS CHUNKING_STRATEGY VARCHAR;
ALTER TABLE KNOWLEDGE_CHUNKS ADD COLUMN IF NOT EXISTS CHUNKER_VERSION VARCHAR;
ALTER TABLE KNOWLEDGE_CHUNKS ADD COLUMN IF NOT EXISTS EFFECTIVE_TAGS VARIANT;

CREATE TABLE IF NOT EXISTS KNOWLEDGE_INGESTION_JOBS (
    JOB_ID VARCHAR NOT NULL,
    DOCUMENT_ID VARCHAR NOT NULL,
    VERSION NUMBER(10,0) NOT NULL,
    STATE VARCHAR NOT NULL,
    CURRENT_STEP VARCHAR,
    PROGRESS_PERCENT NUMBER(5,2) DEFAULT 0,
    STARTED_AT TIMESTAMP_NTZ,
    COMPLETED_AT TIMESTAMP_NTZ,
    ERROR_CODE VARCHAR,
    ERROR_MESSAGE VARCHAR,
    STEP_DETAILS VARIANT,
    REQUESTED_BY VARCHAR NOT NULL,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_KNOWLEDGE_INGESTION_JOBS PRIMARY KEY (JOB_ID)
)
COMMENT = 'Durable ingestion state and step-level diagnostics.';

CREATE TABLE IF NOT EXISTS KNOWLEDGE_EVENTS (
    EVENT_ID VARCHAR NOT NULL,
    EVENT_TYPE VARCHAR NOT NULL,
    REQUEST_ID VARCHAR,
    USER_NAME VARCHAR NOT NULL,
    SESSION_ID VARCHAR,
    DOCUMENT_ID VARCHAR NOT NULL,
    COLLECTION_ID VARCHAR,
    QUESTION VARCHAR,
    NORMALIZED_QUERY VARCHAR,
    APPLIED_FILTERS VARIANT,
    RETRIEVED_CHUNK_IDS ARRAY,
    ANSWER VARCHAR,
    CITATIONS VARIANT,
    MODEL VARCHAR,
    INPUT_TOKENS NUMBER(38,0),
    OUTPUT_TOKENS NUMBER(38,0),
    SEARCH_LATENCY_MS NUMBER(38,0),
    GENERATION_LATENCY_MS NUMBER(38,0),
    TOTAL_LATENCY_MS NUMBER(38,0),
    FEEDBACK VARCHAR,
    ERROR_DETAILS VARIANT,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_KNOWLEDGE_EVENTS PRIMARY KEY (EVENT_ID)
)
COMMENT = 'Search, answer, ingestion, publication, feedback, and error audit events.';

CREATE TABLE IF NOT EXISTS KNOWLEDGE_EVALUATION_CASES (
    EVALUATION_ID VARCHAR NOT NULL,
    COLLECTION_ID VARCHAR NOT NULL,
    QUESTION VARCHAR NOT NULL,
    EXPECTED_DOCUMENT_IDS ARRAY,
    EXPECTED_CHUNK_IDS ARRAY,
    REFERENCE_ANSWER VARCHAR,
    ANSWERABLE BOOLEAN NOT NULL,
    CATEGORY VARCHAR,
    STATUS VARCHAR NOT NULL DEFAULT 'ACTIVE',
    CREATED_BY VARCHAR NOT NULL,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_KNOWLEDGE_EVALUATION_CASES PRIMARY KEY (EVALUATION_ID)
)
COMMENT = 'Frozen questions and expected evidence for retrieval and grounding evaluation.';

CREATE TABLE IF NOT EXISTS KNOWLEDGE_CHUNKING_EVALUATIONS (
    EVALUATION_RUN_ID VARCHAR NOT NULL,
    VARIANT_ID VARCHAR NOT NULL,
    COLLECTION_ID VARCHAR,
    DOCUMENT_ID VARCHAR NOT NULL,
    CHUNKER_VERSION VARCHAR NOT NULL,
    CONFIG VARIANT NOT NULL,
    METRICS VARIANT NOT NULL,
    CREATED_BY VARCHAR NOT NULL,
    CREATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_KNOWLEDGE_CHUNKING_EVALUATIONS
        PRIMARY KEY (EVALUATION_RUN_ID, VARIANT_ID, DOCUMENT_ID)
)
COMMENT = 'Non-production chunking experiment results for variants A, B, and C.';

CREATE OR REPLACE VIEW KNOWLEDGE_LIBRARY_SUMMARY AS
SELECT
    D.DOCUMENT_ID,
    D.VERSION,
    D.TITLE,
    D.COLLECTION_ID,
    C.COLLECTION_NAME,
    D.SECURITY_DOMAIN,
    D.DOCUMENT_TYPE,
    D.LANGUAGE,
    D.EFFECTIVE_FROM,
    D.EFFECTIVE_TO,
    D.STATUS,
    D.IS_CURRENT_VERSION,
    D.PAGE_COUNT,
    D.CHUNK_COUNT,
    D.IMAGE_COUNT,
    D.IMAGE_WARNING_COUNT,
    D.PROCESSING_VERSION,
    D.PROCESSING_WARNINGS,
    D.UPLOADED_BY,
    D.UPLOADED_AT,
    D.PUBLISHED_BY,
    D.PUBLISHED_AT,
    D.UPDATED_AT,
    J.JOB_ID,
    J.STATE AS JOB_STATE,
    J.CURRENT_STEP,
    J.PROGRESS_PERCENT,
    J.ERROR_MESSAGE
FROM KNOWLEDGE_DOCUMENTS D
LEFT JOIN KNOWLEDGE_COLLECTIONS C
    ON C.COLLECTION_ID = D.COLLECTION_ID
LEFT JOIN KNOWLEDGE_INGESTION_JOBS J
    ON J.DOCUMENT_ID = D.DOCUMENT_ID
   AND J.VERSION = D.VERSION
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY D.DOCUMENT_ID, D.VERSION
    ORDER BY J.CREATED_AT DESC NULLS LAST
) = 1;

MERGE INTO KNOWLEDGE_COLLECTIONS T
USING (
    SELECT
        'GENERAL' AS COLLECTION_ID,
        'General Knowledge' AS COLLECTION_NAME,
        'Default internal knowledge collection.' AS DESCRIPTION,
        'English' AS DEFAULT_LANGUAGE,
        'INTERNAL' AS SECURITY_DOMAIN,
        PARSE_JSON('{"chunking":{"strategy":"markdown_section_v2","page_policy":"page_aware","max_raw_characters":1800,"overlap_characters":200,"minimum_merge_characters":350,"preferred_search_text_tokens":480,"maximum_search_text_tokens":512,"chunker_version":"markdown_section_v2","embedding_model":"snowflake-arctic-embed-m-v1.5"}}') AS INGESTION_CONFIG,
        PARSE_JSON('{"candidate_limit":20,"max_chunks_per_document":2,"reranking":true}') AS SEARCH_CONFIG,
        CURRENT_USER() AS CREATED_BY
) S
ON T.COLLECTION_ID = S.COLLECTION_ID
WHEN NOT MATCHED THEN INSERT (
    COLLECTION_ID, COLLECTION_NAME, DESCRIPTION, DEFAULT_LANGUAGE,
    SECURITY_DOMAIN, INGESTION_CONFIG, SEARCH_CONFIG, STATUS, CREATED_BY
) VALUES (
    S.COLLECTION_ID, S.COLLECTION_NAME, S.DESCRIPTION, S.DEFAULT_LANGUAGE,
    S.SECURITY_DOMAIN, S.INGESTION_CONFIG, S.SEARCH_CONFIG, 'ACTIVE', S.CREATED_BY
);

-- Upgrade only the original legacy GENERAL configuration. Explicit collection-level
-- markdown_section_v2 settings remain untouched.
UPDATE KNOWLEDGE_COLLECTIONS
SET INGESTION_CONFIG = PARSE_JSON(
        '{"chunking":{"strategy":"markdown_section_v2","page_policy":"page_aware","max_raw_characters":1800,"overlap_characters":200,"minimum_merge_characters":350,"preferred_search_text_tokens":480,"maximum_search_text_tokens":512,"chunker_version":"markdown_section_v2","embedding_model":"snowflake-arctic-embed-m-v1.5"}}'
    ),
    UPDATED_AT = CURRENT_TIMESTAMP()
WHERE COLLECTION_ID = 'GENERAL'
  AND COALESCE(INGESTION_CONFIG:chunking:strategy::STRING, '') = '';

MERGE INTO KNOWLEDGE_COLLECTION_ACL T
USING (
    SELECT 'GENERAL' COLLECTION_ID, 'ALL' PRINCIPAL_TYPE, '*' PRINCIPAL_NAME,
           'READ' PERMISSION, CURRENT_USER() GRANTED_BY
    UNION ALL
    SELECT 'GENERAL', 'ALL', '*', 'UPLOAD', CURRENT_USER()
    UNION ALL
    SELECT 'GENERAL', 'USER', 'vinoth.manoharan@syneoshealth.com', 'PUBLISH', CURRENT_USER()
    UNION ALL
    SELECT 'GENERAL', 'USER', CURRENT_USER(), 'READ', CURRENT_USER()
    UNION ALL
    SELECT 'GENERAL', 'USER', CURRENT_USER(), 'UPLOAD', CURRENT_USER()
    UNION ALL
    SELECT 'GENERAL', 'USER', CURRENT_USER(), 'PUBLISH', CURRENT_USER()
    UNION ALL
    SELECT 'GENERAL', 'USER', CURRENT_USER(), 'ADMIN', CURRENT_USER()
) S
ON T.COLLECTION_ID = S.COLLECTION_ID
AND T.PRINCIPAL_TYPE = S.PRINCIPAL_TYPE
AND T.PRINCIPAL_NAME = S.PRINCIPAL_NAME
AND T.PERMISSION = S.PERMISSION
WHEN NOT MATCHED THEN INSERT (
    COLLECTION_ID, PRINCIPAL_TYPE, PRINCIPAL_NAME, PERMISSION, GRANTED_BY
) VALUES (
    S.COLLECTION_ID, S.PRINCIPAL_TYPE, S.PRINCIPAL_NAME, S.PERMISSION, S.GRANTED_BY
);

DESCRIBE TABLE KNOWLEDGE_COLLECTIONS;
DESCRIBE TABLE KNOWLEDGE_COLLECTION_ACL;
DESCRIBE TABLE KNOWLEDGE_DOCUMENTS;
DESCRIBE TABLE KNOWLEDGE_DOCUMENT_PAGES;
DESCRIBE TABLE KNOWLEDGE_DOCUMENT_IMAGES;
DESCRIBE TABLE KNOWLEDGE_CHUNKS;
DESCRIBE TABLE KNOWLEDGE_INGESTION_JOBS;
DESCRIBE TABLE KNOWLEDGE_EVENTS;
DESCRIBE TABLE KNOWLEDGE_EVALUATION_CASES;
DESCRIBE TABLE KNOWLEDGE_CHUNKING_EVALUATIONS;
DESCRIBE VIEW KNOWLEDGE_LIBRARY_SUMMARY;
