USE WAREHOUSE WH_COMMUNICATIONS__EU__DER;
USE DATABASE COMMUNICATIONS__EU__DER__DEV;

SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('PFIZER_ANTIINF', 'KNOWLEDGE_HUB')
  AND TABLE_NAME IN (
    'KNOWLEDGE_COLLECTIONS',
    'KNOWLEDGE_DOCUMENTS',
    'KNOWLEDGE_CHUNKS',
    'KNOWLEDGE_EVENTS'
  )
ORDER BY TABLE_SCHEMA, TABLE_NAME;

SELECT
    (SELECT COUNT(*) FROM PFIZER_ANTIINF.KNOWLEDGE_COLLECTIONS) AS ANTIINF_COLLECTIONS,
    (SELECT COUNT(*) FROM PFIZER_ANTIINF.KNOWLEDGE_DOCUMENTS) AS ANTIINF_DOCUMENTS,
    (SELECT COUNT(*) FROM PFIZER_ANTIINF.KNOWLEDGE_CHUNKS) AS ANTIINF_CHUNKS,
    (SELECT COUNT(*) FROM KNOWLEDGE_HUB.KNOWLEDGE_DOCUMENTS) AS ORIGINAL_DOCUMENTS,
    (SELECT COUNT(*) FROM KNOWLEDGE_HUB.KNOWLEDGE_CHUNKS) AS ORIGINAL_CHUNKS;

SHOW CORTEX SEARCH SERVICES LIKE 'KNOWLEDGE_SEARCH'
    IN SCHEMA PFIZER_ANTIINF;

SHOW STREAMLITS LIKE 'PFIZER_ANTIINF'
    IN SCHEMA PFIZER_ANTIINF;
